### ISSUE TITLE
Read options in ~/.gnupg/gpg.conf

### ISSUE THREAD

**Issue by imran-uk** [seancolyer/gmail-crypt#25]
Hi Sean, first off - thanks very much for creating this extension. 

I noticed that it does not seem to respect the setting for "personal-digest-preferences" in the config.

I use the extension for clearsign only and I noticed it was SHA1:

    -----BEGIN PGP SIGNED MESSAGE----- 
    Hash: SHA1

SHA256 seems to be best practice so I wanted it to respect my config setting of:
personal-digest-preferences SHA256

How about just making a change to pick up the settings in the default config file?

**Comment by seancolyer** [comment]
Same issue as #27. The defaults have long been made sane (SHA-256).

Unfortunately, the actual request of loading from ~/ will be impossible because of limitations around chrome extensions. I am closing.

If this is a major issue, please re-open and we can evaluate other options (perhaps having users select a config file to load in).
